---
title: "Research"
---

<!-- One paragraph per paper, newest (top) to oldest (bottom). Probably use a standard APSA style. Include a DOI and hyperlink for all published papers. If you have polished working papers, include links to those as well. -->

My research examines how citizens form and change their political opinions. A complete list is on my CV.


Working Papers

Case, Sarah. 2026. "Behind the Count: How Transparency in Election Audits Can Reduce Voter Confidence." Working paper.

Sarah Case, Hill, Taylor J., Caroline Robbins, and Yusaku Horiuchi. 2026. "Review of Conjoint Experiments Within the Discipline and Recommendations for Interpretation." Working paper.

Atkeson, Lonna, Y. Li, A. Culter, Sarah Case, and M. Wang Dunietz. 2026. "Election Transparency: Do Postelection Audits Improve Voter Confidence?" Working paper.

Atkeson, Lonna, Y. Li, Sarah Case, and M. Arceo-Miranda. 2026. "2024 Florida Election Study." Working paper.

Case, Sarah. 2025. "Did We Move On? Effects of Cross-Pressure Attitudes Between Gender and Partisanship with the #MeToo Movement." Working paper.

Case, Sarah. 2025. "Layers of Trust: Understanding Voter Confidence Across Electoral Levels in the United States, 2008–2024." Working paper.

Early Projects

"A Paper Being Written."